apiVersion: apps/v1
kind: Deployment
metadata:
  name: camelready-deployment
  labels:
    app: camelready
spec:
  replicas: 3
  selector:
    matchLabels:
      app: camelready
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/scheme: "http"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
      labels:
        app: camelready
    spec:
      containers:
        - name: camelready
          image: docker.io/library/camelready:1.0
          ports:
            - containerPort: 8888
              name: ready
              protocol: TCP
            - containerPort: 8080
              name: metrics
              protocol: TCP
          readinessProbe:
            httpGet:
              port: ready
              path: /ready
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 1000
          volumeMounts:
            - name: jmx-exporter-config
              mountPath: /config.yaml
              subPath: config.yaml
      volumes:
        - name: jmx-exporter-config
          configMap:
            name: jmx-exporter-config
            items:
              - key: config.yaml
                path: config.yaml