apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: camel-ready-servicemonitor
  namespace: default
  labels:
    app: camelready
spec:
  selector:
    matchLabels:
      app: camelready
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s

      
