apiVersion: v1
kind: Service
metadata:
  name: camel-metrics-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/scheme: "http"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
  labels:
    app: camelready
spec:
  selector:
    app: camelready
  ports:
    - name: metrics
      protocol: TCP
      port: 8080
      targetPort: 8080